import Archer from './components/Archer/Archer'
import Footer from './components/Footer/Footer'
import NavBar from './components/NavBar/NavBar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        <title>Kevin Ceron</title>
        <link href="https://fonts.googleapis.com/css2?family=VT323&display=swap" rel="stylesheet"/>
      </head>
      <body>
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
